version: '3.8'

services:
    books_app:
        build:
            context: ./book_service
            dockerfile: Dockerfile
        container_name: books_service
        ports:
            - "9000:9000"
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=books_db
            - DB_PORT=3306
        volumes:
            - ./book_service:/var/www/html
        depends_on:
            - books_db

    books_db:
        image: mysql:8.0
        container_name: books_db
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=books_db
            - MYSQL_USER=books_root
            - MYSQL_PASSWORD=password
        volumes:
            - books_db_data:/var/lib/mysql

    books_nginx:
        image: nginx:latest
        container_name: books_nginx
        ports:
            - "9002:80"
        volumes:
            - ./book_service/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - books_app

    reviews_app:
        build:
            context: ./review_service
            dockerfile: Dockerfile
        container_name: reviews_service
        ports:
            - "9001:9000"
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=reviews_db
            - DB_PORT=3306
        volumes:
            - ./review_service:/var/www/html
        depends_on:
            - reviews_db

    reviews_db:
        image: mysql:8.0
        container_name: reviews_db
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=reviews_db
            - MYSQL_USER=reviews_root
            - MYSQL_PASSWORD=password
        volumes:
            - reviews_db_data:/var/lib/mysql

    reviews_nginx:
        image: nginx:latest
        container_name: reviews_nginx
        ports:
            - "9003:80"
        volumes:
            - ./review_service/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - reviews_app

volumes:
    books_db_data:
    reviews_db_data:
